export const PROMPT_LIBRARY = [
  "Most likely to argue with a GPS",
  "Most likely to accidentally start a cult",
  "Most likely to name their Roomba",
  "Most likely to fake a phone call to escape a conversation",
  "Most likely to still have Internet Explorer bookmarks",
  "Most likely to cry at a dog food commercial",
  "Most likely to survive a zombie apocalypse (somehow)",
  "Most likely to eat the last slice without asking",
  "Most likely to become a conspiracy theorist",
  "Most likely to get lost in IKEA and just give up",
  "Most likely to befriend a raccoon",
  "Most likely to order the weirdest thing on the menu",
  "Most likely to reply-all by accident",
  "Most likely to go viral for the wrong reason",
  "Most likely to talk to strangers on public transport",
  "Most likely to forget their own birthday",
  "Most likely to dramatically quit a job",
  "Most likely to bring a blanket to a party",
  "Most likely to have a backup plan for their backup plan",
  "Most likely to get into an argument with a bot",
  "Most likely to spend 3 hours choosing a movie and then fall asleep",
  "Most likely to get banned from a trivia night",
  "Most likely to go off the grid",
  "Most likely to become a professional taste tester",
  "Most likely to believe they can fix it themselves (they cannot)",
  "Most likely to be on a first-name basis with their mail carrier",
  "Most likely to be the reason there are new rules",
  "Most likely to still be awake at 4am for no reason",
  "Most likely to write a strongly-worded letter",
  "Most likely to move to a cabin in the woods",
  "Most likely to accidentally text the wrong group chat",
  "Most likely to get into a heated debate about fonts",
  "Most likely to be adopted by a random cat",
  "Most likely to have strong opinions about store layouts",
  "Most likely to show up to the wrong event and stay anyway",
  "Most likely to have the most embarrassing search history",
  "Most likely to use a spreadsheet for meal planning",
  "Most likely to apologize to inanimate objects",
  "Most likely to be the last to leave a party",
  "Most likely to have 47 browser tabs open right now",
  "Most likely to take a detour and call it an adventure",
  "Most likely to be genuinely good at something weird",
  "Most likely to have a life-changing realization in a parking lot",
  "Most likely to forget why they walked into a room",
  "Most likely to have a rivalry with a pigeon",
  "Most likely to become famous after everyone else gives up",
  "Most likely to get emotionally attached to a side character",
  "Most likely to be weirdly good at accents",
  "Most likely to give a TED talk nobody asked for",
  "Most likely to be the hero in a disaster film",
  "Most likely to own a sword",
  "Most likely to still be using an AUX cord",
  "Most likely to have a themed birthday party at 40",
  "Most likely to ask for manager (rightfully so)",
  "Most likely to leave a detailed review for every purchase",
  "Most likely to have a plant named after a historical figure",
  "Most likely to fall asleep mid-sentence",
  "Most likely to be the first one to skinny dip",
  "Most likely to open a food truck",
  "Most likely to have matching luggage and a rolling schedule",
  "Most likely to get shushed at a library (twice)",
];

export function pickPrompts(count = 5): string[] {
  const shuffled = [...PROMPT_LIBRARY].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
